### ISSUE TITLE
failed: Error: Failed to publish one or more assets

### ISSUE THREAD

**Issue by boringContributor** [dabit3/cdk-graphql-backend#2]
When I clone, install and deploy the repo I get the following error:

[100%] fail: No bucket named 'cdktoolkit-stagingbucket-nisbmeck9lcx'. Is account xyz bootstrapped?

The exact error message is:

AppsyncCdkAppStack failed: Error: Failed to publish one or more assets. See the error messages above for more information.
    at Object.publishAssets (/usr/local/lib/node_modules/aws-cdk/lib/util/asset-publishing.ts:25:11)
    at Object.deployStack (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:229:3)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:180:24)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:204:9)
Failed to publish one or more assets. See the error messages above for more information.

cdk bootstrap is not the solution. Did you face this error or point out what is wrong here? I use node v14.15.0 and I am on the macbook pro.

Thx!

**Comment by boringContributor** [comment]
Solution: Delete cdk toolkit stack in cloudformation and bootstrap again.
